name: vneduvanced
description: A custom, ad-free score overview for Vietnamese students.

publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.0.15
  flutter_markdown: ^0.6.13
  dio: ^4.0.6
  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  open_file_plus: ^3.3.0
  package_info_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
